[pytest]
python_files = test_*.py # какие файлы считать тестами
python_functions = test_*  # какие функции считать тестами
addopts = -vv -p no:cacheprovider
markers =
    type: проверка на верность типа данных результата функции
    btc: проверка тестов для биткоина
    eth: проверка тестов для эфира
    token: проверка tokenID
    currency: проверка currencyId
    count_offers: поверка count_offers
    valid_price: проверка valid_price
    valid_quantity: проверка valid_quantity